runtime: python
runtime_config:
  operating_system: "ubuntu18"
  runtime_version: "3.8"
  #entrypoint: "streamlit run --server.port=8080 --server.address=0.0.0.0 --server.enableCORS=false --server.enableWebsocketCompression=false --server.enableXsrfProtection=false --server.headless=true machine_gca.py"
  entrypoint: streamlit run --server.port=8080 --server.address=0.0.0.0 --server.enableCORS=false --server.enableWebsocketCompression=false --server.enableXsrfProtection=false --server.headless=true https://github.com/subhabaha/MachineRunRender/blob/main/machine_gca.py
env: flex
network:
  session_affinity: true

