# config.yaml

# Streamlit configuration
streamlit:
  page_title: "Machine Status App"
  page_icon: "🤖"
  layout: "wide"

# Model and video configuration
model:
  model_path: "machine_model_5jan10pm.h5"
  video_path: "rtsp://admin:Admin@123@125.19.34.95:554/cam/realmonitor?channel=1&subtype=0"

# Email configuration
email:
  sender_email: "chandrapaulcs2001@gmail.com"
  sender_password: "lbjc utkq kawe fcvd"
  recipient_email: "chandrapauldas01@gmail.com"
  email_subject: "⚠️ Warning! Machine Status changed ⚠️"

# Streamlit sidebar options
sidebar:
  menu_title: "Main Menu"
  options:
    - "Machine Status"
    - "Machine runtime log"
  icons:
    - "lightning-charge-fill"
    - "list-columns"
  default_index: 0